### ISSUE TITLE
RFv2 compilation issues

### ISSUE THREAD

**Issue by itwysgsl** [bschn2/rainforest#12]
Purpose of this issue - track all little errors I've encountered during compilation of rfv2.

**Comment by itwysgsl** [comment]
@bschn2 you used `template` as argument name [here](https://github.com/bschn2/rainforest/blob/rfv2/rfv2.h#L41), but since `template` is [reserved](http://www.cplusplus.com/doc/oldtutorial/templates/) word in c++ it cause some troubles during compilation. I think it would be better rename this argument to something like `rambox_template`.

**Comment by itwysgsl** [comment]
Also I got `error: unknown type name 'size_t'` messages because `rf_crc32.c` and `rfv2_core.c` files missing `stdlib.h` header file.

**Comment by itwysgsl** [comment]
When I'm trying to include C code inside C++ this error pop up:
```
./rfv2/rfv2.c:421:39: error: arithmetic on a pointer to void
                crc = rf_crc32_8(crc, *(uint8_t*)msg++);
```

**Comment by itwysgsl** [comment]
On ubuntu this code just give warning:
```
./rfv2/rfv2.c:421:39: warning: ISO C++ forbids incrementing a pointer of type ‘const void*’ [-Wpointer-arith]
   crc = rf_crc32_8(crc, *(uint8_t*)msg++);
```

**Comment by itwysgsl** [comment]
This 2 lines https://github.com/bschn2/rainforest/blob/rfv2/rfv2_test.c#L155-L156
uses odd data type `uint` which I never saw before. It causes build issues on macOS, but after I replaced it with `unsigned int` everything compiled just fine.

P.s. Seams liks this little changes don't break anythign :)
```
Single hash:
valid: ad43e40193aee36e9fcb8307956a74a3.91a7f7ee087ee5e2e410230d708500d5
256-loop hash:
valid: b7981703e677f598226320c8fa1c77ae.c7cc0654b9930ba28a52baedeeba5563
```

**Comment by itwysgsl** [comment]
Btw @bschn2 it may be my mistake, but why it produces this strange hash with dot in the middle?
```
./test -m "This is test message"
out: 5ed58d3f8f9d60f795f8ad094c7c56c0.c1eb5fc0338d03745c6ba64bfeeca263
```

P.s. I think reason is in [this](https://github.com/bschn2/rainforest/blob/rfv2/rfv2_test.c#L126-L127) print statement, but is there any reason why it contains dot?

**Comment by bschn2** [comment]
> When I'm trying to include C code inside C++ this error pop up:
> 
> ```
> ./rfv2/rfv2.c:421:39: error: arithmetic on a pointer to void
>                 crc = rf_crc32_8(crc, *(uint8_t*)msg++);
> ```

I thought we addressed all of these already in the past, apparently not. Ah I got it, it's in the new function. Same fix as usual :

     uint8_t msg8 = (uint8_t *)msg;
  ...
     and use *msg8 in the loop.

**Comment by bschn2** [comment]
> This 2 lines https://github.com/bschn2/rainforest/blob/rfv2/rfv2_test.c#L155-L156
> uses odd data type `uint` which I never saw before. It causes build issues on macOS, but after I replaced it with `unsigned int` everything compiled just fine.
> 
> P.s. Seams liks this little changes don't break anythign :)
> 
> ```
> Single hash:
> valid: ad43e40193aee36e9fcb8307956a74a3.91a7f7ee087ee5e2e410230d708500d5
> 256-loop hash:
> valid: b7981703e677f598226320c8fa1c77ae.c7cc0654b9930ba28a52baedeeba5563
> ```

Sorry, it proves that I copied the code from the opencl one and forgot to rename uint to uint32_t because uint is also defined on linux. Feel free to modify it as well! And I confirm that besides this it is harmless.

**Comment by bschn2** [comment]
> Btw @bschn2 it may be my mistake, but why it produces this strange hash with dot in the middle?
> 
> ```
> ./test -m "This is test message"
> out: 5ed58d3f8f9d60f795f8ad094c7c56c0.c1eb5fc0338d03745c6ba64bfeeca263
> ```
> 
> P.s. I think reason is in [this](https://github.com/bschn2/rainforest/blob/rfv2/rfv2_test.c#L126-L127) print statement, but is there any reason why it contains dot?

Because at 53 my sight is diminishing and during debugging sessions I really needed to spot each 4-byte (hence 8-digit) block. I found that having a dot in the middle of the whole hash helped me a lot. We could remove it by now. @ClashLuke already has a pending patch to redo the print256() function, it might be the right moment to get rid of this dot.

**Comment by itwysgsl** [comment]
Also I think that we should add `rfv2_raminit` to header because it's required to init rambox which will be passed to `rfv2_hash` 🤔

**Comment by itwysgsl** [comment]
So far everyting seams to be fixed. Clossing this issue :)
