### ISSUE TITLE
Different Hash missmatches.

### ISSUE THREAD

**Issue by LinuXperia** [bschn2/rainforest#22]
Hi.

just wanted to let you know there is a problem with mismatch of Hash calculation
one time on the Node side and one time on the CPUMiner side.

I spent last days trying to figure out why does the Node calculate a different Block Hash
than the CPUMiner calculated Block Hash.

This should normally not happen but it happens at the Moment.

Can somebody look into this issue and maybe tell me what exactly is wrong.

As said this does not make sense for me:
It is totaly unexpected.

I have the CPUMiner and the Node on the same Machine
so diffeence between 64 Bit Mashine and 32 Bit Mashine should be not the Problem.

The Node and the CPU miner runs on a 32 Bit i686 Ubuntu linux OS

here is the ouput one time of the CPU Miner when he submitt the Block 

> BINGOOOO BLOCK NONCE FOUND SUBMITING TO NETWORK !!!!  NONCE = 800005e4
> [2019-04-12 23:43:06] e703e0fdb87277b39737c157f620ed92be16adf086fdaf8fe4535f69617c58fd

and here is what the Node does come up with a Rainforest Hash 

> RainForest HASH: 42ff733419c924067d1d6ddc565ed31c63b80b48793cec2a1b63323f6ad4ed7c
> Extracted RainForest HASH:
> [0] 1b63323f6ad4ed7c
> [1] 63b80b48793cec2a
> [2] 7d1d6ddc565ed31c
> [3] 42ff733419c92406
> 2019-04-12 21:43:07 ERROR: ProcessNewBlock: AcceptBlock FAILED (proof of work failed), Bad hash: 42ff733419c924067d1d6ddc565ed31c63b80b48793cec2a1b63323f6ad4ed7c
> 
> 
> 

I am extracting the Rainforest Hash like this in the Node to print all this Info in MicroBitcoin/src/pow.cpp

>         // CHECK RAINFOREST HASH
>         std::cout << "RainForest HASH: " << hash.GetHex() << "\n";
> 
>         // Extract Hash
>         uint64_t rf_hash[4];
>         rf_hash[0] = hash.GetUint64(0);
>         rf_hash[1] = hash.GetUint64(1);
>         rf_hash[2] = hash.GetUint64(2);
>         rf_hash[3] = hash.GetUint64(3);

Its pretty clear that the Node calculates a different Rainforest Hash Algorithm
inside the file
MicroBitcoin/src/primitives/block.cpp
and submitt it to
MicroBitcoin/src/pow.cpp as a wrong hash

This should not happen.

As said i spent days now to figure out why this is happening on the same mashine but it does not make sense for me.

**Comment by bschn2** [comment]
Hello Sir,

I'm sorry to read this. I'm not sure what you call "the node", I understand it's your 32 bit machine. I'll have a look as I don't understand what could cause this at the moment. Did you try rfv2_test -c on it ? It would help spot the causes of the error.

Thank you!

**Comment by wtarreau** [comment]
I'm seeing some "long" being used in the code there (especially the clrsbl implementation). These ones would be 32-bit on 32-bit platforms. They're very likely one possible cause.

**Comment by wtarreau** [comment]
At least if I build rfv2_test in i586 mode it says this:
$ ./rfv2_test -c
sum1=363985 sum5=-398506 p1=53512 p5=23787 d=4369.000000

So indeed something is wrong there.

**Comment by wtarreau** [comment]
It was indeed the use of longs in rftest and the builtin functions which needed to use _ll instead of _l. Now on i586 I get the correct hashes. I'm sending a PR in parallel. I also fixed a nasty sigalarm which interrupts the bench mode there.

**Comment by bschn2** [comment]
Excellent, thank you a lot, Sir! I have merged your pull request, which as usual, was very clean.

**Comment by wtarreau** [comment]
Thanks.
I noticed that there are still the outdated comments about performance on various devices at the top of all files. It's probably time to remove them ? Maybe we should also add a warning for incomplete fp64 implementations where this could fail ?

**Comment by bschn2** [comment]
Oh yes you're right. I have to review these comments and update them to the newer design. I also want to acknowledge participation of the people here who have provided significant inputs to make this project a reality.

**Comment by LinuXperia** [comment]
@wtarreau @bschn2 

Woow Thank you very much for your Support !
You are both Excelent Gentlemens and very skilled Coders and Engineers.

Please let me know when everything is patched so i can sync the rfv2 Code and recompile verything !
Thanks a lot will report back and close this Issue as soon it works.

**Comment by wtarreau** [comment]
On Sat, Apr 13, 2019 at 12:47:40PM -0700, LinuXperia wrote:
> @wtarreau @bschn2 
> 
> Woow Thank you very much for your Support !
> You are both Excelent Gentlemens and Coders.
> 
> Please let me know when everything is patched so i can sync the rfv2 Code and
> recompile verything !
> Thanks a lot will report back and close this Issue as soon it works.

I believe my pull request was merged, I can't check at the moment (just
e-mail access). Please just pull, rfv2, if you see me in the few last
commits it should be OK.

Willy

**Comment by LinuXperia** [comment]
Okey thank you @wtarreau

**Comment by LinuXperia** [comment]
HI.

Just wanted report that after implementing the new changes
i still get different Hash Calculations one time on the CPUMiner Side
and one time on the MicroBitcoin Node side.

I had already run dozens of trail and error trails to isolate the problem before .
and got same broken rf_test ouput like @wtarreau 

> sum1=363985 sum5=-398506 p1=53512 p5=23787 d=4369.000000

Now after fully resync of the rainforest latest patches at least i get two hashes calculated but it looks like
the rainforest algorithm calculate two different wrong hashes on 32 Bit OS Machines

Here is what rfv2_test output after compilation on my i686 Machine after compiling rainforest with the latest Patches.

This two different Hash Outputs for same Data is really odd and incoherent !

It say that a Invalid Hash was Calculated and is not what is expected at least on my side where i compiled it.

I just used as compilation Flags "-O3 -march=native" and nothing else 

> ./rfv2_test -c
> Single hash:
>  **invalid**: fe01eb35079a8b97ae737397f0a93e6263e5b83f32bc93db80a5ca2193bab574
> **expected**: c42265356de90939dad4c1da00e0cc89dd4272dcc6a55e242a2930e8a7ca52d2
> 

The new patched CPUMiner and Node Code calculate also two different Hashes

CPUMiner Hash

> BINGOOOO BLOCK NONCE FOUND SUBMITING TO NETWORK !!!!  NONCE = 000001c3
> [2019-04-14 21:10:27] 3d1fd24eac96b795c606dfbca201c176f8633a3464ff102e59eb3fee162f16ac
> [2019-04-14 21:10:27] CPU #0: 192.66 H/s

MicroBitcoin Hash

> RainForest HASH: da4f7d3056f577bfa068334c0394eb16655ab7b54f534737e49e519447f0d3fa
> Extracted RainForest HASH:
> [0] e49e519447f0d3fa
> [1] 655ab7b54f534737
> [2] a068334c0394eb16
> [3] da4f7d3056f577bf

**The Strange Part is that RainForest Calculate with same Code two Different Hashes at different times !**

**Comment by wtarreau** [comment]
On Sun, Apr 14, 2019 at 12:28:58PM -0700, LinuXperia wrote:
> I just used as compilation Flags "-O3 -march=native" and nothing else 
> 
> > ./rfv2_test -c
> > Single hash:
> >  **invalid**: fe01eb35079a8b97ae737397f0a93e6263e5b83f32bc93db80a5ca2193bab574
> > **expected**: c42265356de90939dad4c1da00e0cc89dd4272dcc6a55e242a2930e8a7ca52d2

Strange. I can get a wrong hash (a different one) when building with
-ffast-math. What compiler version do you use ? Could you please send the
output of "gcc -v" ?

Also, could you please try to build with -O2 instead of -O3, and try with
-DRF_NOASM in order to help spot if it's in the asm parts or in the generic
code ?

I suspect it might be related to another builtin that is not well defined
for use as 64-bit value.

Hmmm interesting, when building with gcc-3.4 I can get some warnings about
constants being too large for longs when -stc=c99 is not set. It might be
possible that other versions could silently truncate them. However the
hash is still valid in this case for me.

Willy

**Comment by wtarreau** [comment]
Here's the cleanup I've done here to allow it to build without warning
nor error without -std=c99. I'm not convinced it's related to your
problem but we never know :-/

If the attachment doesn't work, please check https://wtarreau@github.com/wtarreau/rainforest.git or wait for the pull-req to be merged :-)

Willy


diff --git a/rfv2_core.c b/rfv2_core.c
index a7af85d..5c6de6f 100644
--- a/rfv2_core.c
+++ b/rfv2_core.c
@@ -249,9 +249,9 @@ static inline uint64_t rf_revbit64(uint64_t v)
 #if !defined(RF_NOASM) && defined(__aarch64__)
 	__asm__ volatile("rbit %0, %1\n" : "=r"(v) : "r"(v));
 #else
-	v = ((v & 0xaaaaaaaaaaaaaaaa) >> 1) | ((v & 0x5555555555555555) << 1);
-	v = ((v & 0xcccccccccccccccc) >> 2) | ((v & 0x3333333333333333) << 2);
-	v = ((v & 0xf0f0f0f0f0f0f0f0) >> 4) | ((v & 0x0f0f0f0f0f0f0f0f) << 4);
+	v = ((v & 0xaaaaaaaaaaaaaaaaULL) >> 1) | ((v & 0x5555555555555555ULL) << 1);
+	v = ((v & 0xccccccccccccccccULL) >> 2) | ((v & 0x3333333333333333ULL) << 2);
+	v = ((v & 0xf0f0f0f0f0f0f0f0ULL) >> 4) | ((v & 0x0f0f0f0f0f0f0f0fULL) << 4);
 #if !defined(RF_NOASM) && defined(__x86_64__)
 	__asm__("bswap %0" : "=r"(v) : "0"(v));
 #else
diff --git a/rfv2_test.c b/rfv2_test.c
index 0776083..0c4b4c0 100644
--- a/rfv2_test.c
+++ b/rfv2_test.c
@@ -124,8 +124,11 @@ void report_bench(int sig)
 
 static void print256(const uint8_t *b, const char *tag)
 {
+	uint8_t i;
+
 	printf("%s: ",tag);
-	for(uint8_t i=0;i<32;i++) printf("%02x",b[i]);
+	for (i = 0; i < 32;i++)
+		printf("%02x",b[i]);
 	printf("\n");
 }
 
@@ -167,7 +170,7 @@ int check_sin()
 		i++;
 	} while (i != stop);
 
-	if (sum1 != 300239689190865 || sum5 != 300239688428374) {
+	if (sum1 != 300239689190865ULL || sum5 != 300239688428374ULL) {
 		printf("sum1=%ld sum5=%ld p1=%u p5=%u d=%f\n",
 		       sum1, sum5, prev1, prev5, d);
 		return 0;

**Comment by wtarreau** [comment]
I've just tried with TCC and it produces correct hashes as well, which
is good news.

Willy

**Comment by wtarreau** [comment]
By the way, how do you test you code against the microbitcoin implementation ? I don't know how to do that. Do you configure a server in cpuminer ? If so which one ?

**Comment by LinuXperia** [comment]
@wtarreau 

Woow you are Great Man!
You solved the Problem.

I had used in a Makefile to compile things faster this configuration

> CC=gcc
> CFLAGS=-O3 -Wall -I. -march=native -ffast-math -pthread -lm
> rfv2_test:	rfv2_test.c
> 		$(CC) rfv2_test.c $(CFLAGS) -o $@

after removing -ffast-math from the compile options i finally get the right
hashes output on my 32 Bit OS Mashine !

> ./rfv2_test -c
> Single hash:
> valid: c42265356de90939dad4c1da00e0cc89dd4272dcc6a55e242a2930e8a7ca52d2
> 256-loop hash:
> valid: d2e67f6b0ba8c3f2a1bd02e5a2f34f233c948c101b9a472fd8e147a427d65b57

You did it @wtarreau  Big Compliments to You and sorry about this flag.
The Problem was this stupid Flag that i used.
On 64Bit Machine with 64Bit OS using this Flag produced right Hashes only on 32 Bit OS it fails to Produce right Hashes when using this Flag !

Thanks a lot for figuring it out and solving the Problem !

here btw the gcc output

> gcc -v
> Using built-in specs.
> COLLECT_GCC=gcc
> COLLECT_LTO_WRAPPER=/usr/lib/gcc/i686-linux-gnu/7/lto-wrapper
> Target: i686-linux-gnu
> Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.3.0-27ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=i686-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-targets=all --enable-multiarch --disable-werror --with-arch-32=i686 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=i686-linux-gnu --host=i686-linux-gnu --target=i686-linux-gnu
> Thread model: posix
> gcc version 7.3.0 (Ubuntu 7.3.0-27ubuntu1~18.04) 


Related to your Question.
I patched the CPU Miner and MicroBitcoin
with thr rfv2 Code and then run both and waited till  CPUMiner found a Block
Normally you can skip the wait and just uncomment the "<= HTarg" line so on each Nonce Calculation a Block is submitted and calculated by the Node.
That way you can test the Implementation on the Miner and the Node side.

I talked with the MicroBitcoin Devs.
They loaded a 32Bit OS VM and tested everything and can confirmed that all is good with hashes.

So i will close now this Issues as it is solved.
MicroBitcoin Devs will anounce soon TestNet Public and go Live i expect with RFV2.
Thanks a Lot for the Help.

**Comment by LinuXperia** [comment]
Looks like testnet is anounced already live without the patches from this work.
Not sure if testnet works on 32 Bit mashines hmmm ....

https://github.com/MicroBitcoinOrg/MicroBitcoin/tree/rfv2

https://github.com/MicroBitcoinOrg/Cpuminer/

The Question is does CPUMiner or MicroBitcoin uses -ffast-math
as a compilation flag anywhere per default by using as a example the ./build
script

if yes then we will have wrong submitted and calculated hashes becouse of this.

**Comment by wtarreau** [comment]
On Mon, Apr 15, 2019 at 05:42:21AM +0000, LinuXperia wrote:
> I had used in a Makefile to compile things faster this configuration
> 
> > CC=gcc
> > CFLAGS=-O3 -Wall -I. -march=native -ffast-math -pthread -lm
> > 
> > rfv2_cpuminer:	rfv2_cpuminer.c
> > 		$(CC) rfv2_cpuminer.c $(CFLAGS) -o $@ 
> 
> after removing -ffast-math from the compile options i finally get the right
> hashes output on my 32 Bit OS Mashine !

Excellent! I'm not very surprised you got trapped with the -ffast-math
flag. It's purposely designed to reduce FP accuracy and trade it for
speed. That's exactly what FPGAs or ASICs would do. Here it shows the
algo will give them some gray hair ;-)

Willy

**Comment by LinuXperia** [comment]
Thank you very much @wtarreau 

You solved the Problem and helped me a lot!
I am closing this Issue.
