### ISSUE TITLE
Floating point critical issues

### ISSUE THREAD

**Issue by itwysgsl** [bschn2/rainforest#26]
@bschn2 @wtarreau This issue is heavily related to #25.
After @djm34 discovered floating point conversion issue in `rfv2_mix_fp_loss` function, I asked @fireice-uk about IEEE 754 support on GPUs (since he have pretty good expertise with floating point algos). And he said that [this](https://github.com/bschn2/rainforest/blob/rfv2/rfv2_core.c#L719-L731) functions also may cause a lot of troubles since it heavily depends on language implemetation and CPU architecture. 

Considering all this info which pop up recently what you think about removing/replacing all floating point operations (at least for now) ?

Since our network ~7 days away from switching to RFv2 this issue is kinda urgent 😅

**Comment by wtarreau** [comment]
Hi!

On Thu, Apr 25, 2019 at 09:37:06AM -0700, iamstenman wrote:
> After @djm34 discovered floating point conversion issue in `rfv2_mix_fp_loss`
> function, I asked @fireice-uk about IEEE 754 support on GPUs (since he have
> pretty good expertise with floating point algos). And he said that
> [this](https://github.com/bschn2/rainforest/blob/rfv2/rfv2_core.c#L719-L731)
> functions also may cause a lot of troubles since it heavily depends on
> language implemetation and CPU architecture. 
> 
> Considering all this info which pop up recently what you think about
> removing/replacing all floating point operations (at least for now) ?

Hmmm this is quite sad, I really loved the principle of the difficulty
added based on compliance vs non-compliance. And the fact that it works
on x86, ARM and some GPUs tends to indicate that it is possible to get
other valid implementations to work. However I agree that if it's too
difficult it can become a problem for your use case.

I still like the principle of the oscillating loop count however, which
is a real pain to map to hardware and even to optimise in long software
pipelines (e.g. no loop unrolling there). A long time ago for a home
project (PCB etcher), I ended up implementing a sine in asm on a 8-bit
microcontroller. I figured it was very easy in the end and I pretty much
see how to do this here using plain C and standard integers. I could
probably propose you a patch to try if you want.

> Since our network ~7 days away from switching to RFv2 this issue is kinda urgent ? 

Wow, I definitely understand! I'll try to get back to my integer sine
wave this evening if nobody beats me at it.

Willy

**Comment by itwysgsl** [comment]
Thanks for fast responce @wtarreau !

**Comment by djm34** [comment]
actually the loop through sine works fine on nvidia.

**Comment by wtarreau** [comment]
On Sat, Apr 27, 2019 at 01:04:20PM -0700, djm34 wrote:
> actually the loop through sine works fine on nvidia. 

Great so probably we should just comment out the fp_loss() function.
It's nice if we can limit last minute changes.

Willy

**Comment by bschn2** [comment]
This one is now addressed in master.
