### ISSUE TITLE
Compiler warnings

### ISSUE THREAD

**Issue by 2acoin** [bschn2/rainforest#3]
We're attempting to compile our code with the Rainforest algo for testing. However, during the compile process we are receiving the following warnings;

https://i.imgur.com/uEOLZpL.png

Are there special compile directives required for this algo?

**Comment by bschn2** [comment]
Hello,
I think it depends on the compiler, some compilers don't like arithmetics on void*. It's possible to cast these to char* instead. Do you see how to proceed ? If you manage to do it, feel free to send a fix.

**Comment by bschn2** [comment]
Hello again,
I have just merged some build fixes that precisely address this issue, please pull again.

**Comment by bschn2** [comment]
I think all these warnings were now addressed.
