### ISSUE TITLE
AES Variant

### ISSUE THREAD

**Issue by ClashLuke** [bschn2/rainforest#6]
Since I don't seem to be able to find any information about it and the security heavily relies on it, I'm asking here.
**What AES variant are you using?** 
Your x86 ASM code appears to be the following
```
movups (%0),  %%xmm0
movups (%1),  %%xmm1
pxor   %%xmm1,%%xmm0
movups 16(%1),%%xmm2
movups 32(%1),%%xmm1
aesenc %%xmm2,%%xmm0
aesenclast %%xmm1,%%xmm0
movups %%xmm0, (%0)
```
which matches pretty well with the unnamed default variant of AES I was able to find.

**Comment by bschn2** [comment]
Hello Sir,
it simply runs two rounds (the full AES contains 11, most AES-based SHA3 candidates use two as well). While at first glance it could appear weaker, these two rounds are executed for each 32-bit input block, and in any case there are at least 4 finishing RF rounds (2 AES rounds each) so you have at least 8+4=12 rounds for only 128 bits in which is already more than the plain AES.
I considered using the full AES algo but I was worried about its not so great performance on low-end GPUs and tried to keep the performance well balanced between devices.

**Comment by ClashLuke** [comment]
I see, so it's AES ECB?
